Fix/new mc 13– layout
e1401/musicolor pull request #26
Opened 2024-01-05 17:53 UTC by MatejaC

2024-01-06 11:02 UTC, e1401 commented
<img width="605" alt="Screenshot 2024-01-06 at 11 56 32" src="https://github.com/e1401/musicolor/assets/38010322/ba26ed9a-eadb-47b1-a257-4eb7c0a7fa4a">
We have a funny situation here, two branches with seemingly the same name but you have used em-dash instead of en-dash on the latter, the dash is longer, and therefore this warning 

<img width="581" alt="Screenshot 2024-01-06 at 12 01 42" src="https://github.com/e1401/musicolor/assets/38010322/a25538aa-b446-4c83-a095-a734053f80d0">

2024-01-06 12:03 UTC, e1401 requested changes
Three easy pieces

2024-01-06 12:03 UTC, e1401 commented on src/components/Footer.tsx
>  const Footer = () => {
consider 
```
const Footer = () => {
    return (
        // <Box
        //   sx={{
        //     display: 'flex',
        //     flexDirection: 'column',
        //     alignItems: 'center',
        //   }}
        // >
        <footer>
            <Box
                display='flex'
                flexDirection='column'
                justifyContent='center'
                alignItems='center'
                height='64px'
                border='1px solid red'
            >
                <Typography variant='caption' color={grey[400]}>
                    Made with ❤️ for colors and music
                </Typography>
            </Box>
        </footer>
    );
};

export default Footer;
```

We need to use semantic footer tag here

2024-01-06 15:03 UTC, e1401 commented
👋 bot hello

2024-01-07 10:03 UTC, e1401 commented
@MatejaC there are conlicts to be resolved in 
src/components/ResultCard.tsx
src/components/SearchBox.tsx
src/hooks/store.ts
yarn.lock

2024-01-07 11:39 UTC, MatejaC commented
closing pull request, conflicts resolved, moving on

2024-01-07 11:39 UTC, closed without merging