Fix/mc 25  starting page redo
e1401/musicolor pull request #42
Opened 2024-02-16 23:06 UTC by MatejaC

2024-02-17 15:13 UTC, e1401 requested changes

2024-02-17 15:13 UTC, e1401 commented on src/components/SearchBox.tsx
> +      <Box minWidth='40vw' width='105%'>
Check Slack and the video example there because it is over 10mb limit

2024-02-17 21:23 UTC, MatejaC commented
Tnx! :)

2024-02-18 10:37 UTC, e1401 approved these changes
✅

2024-03-26 18:13 UTC, e1401 commented
Closed due to inactivity.

2024-03-26 18:13 UTC, closed without merging